const String kSupabaseUrl = 'https://cyfwcgsfdlecnkycpjsk.supabase.co';
const String kSupabaseAnonKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5ZndjZ3NmZGxlY25reWNwanNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxMTgyMTAsImV4cCI6MjA4NTY5NDIxMH0.0k2fMxf4_jqYLKalduhK251yOo8jKnvUnpWepundLus';
